### ISSUE TITLE
Cooperate with Quartz to publish on GitHub Pages

### ISSUE THREAD

**Issue by xplusyi** [yy4382/obsidian-static-site-export#8]
Hi, I am recently looking for methods to publish Obsidian notes to a site like GitHub Pages.
Step 1. Write a note in Obsidian, add a tag "publish: true" as a mark;
Step 2. Run a command to upload the notes (including the embedded notes or images) in step 1 to a specified folder in a Github repo;
Step 3. Github Pages updated according to the new file pushed in automatically, with the features like graph view supported.

As I know, step 3 can be done beautifully by Quartz (https://github.com/DefenderOfBasic/obsidian-quartz-template). [Quartz](https://quartz.jzhao.xyz/) is not a plugin of Obsidian, however, it supports Obsidian very well. It can generate a nice site with GitHub Pages from markdown notes in Obsidian. However, we need to export the published notes to a separate folder for Quartz.

Step 2 can be done with your plugin, I think. I am new to here, and trying to do this.

If you have any other methods to do the similar workflow, please let me know. Thanks a lot.

PS:
I've tried plugin "Digital Garden", which works well with vercel. While I prefer GitHub Pages. This plugin implemented Step 2 conveniently.

**Comment by yy4382** [comment]
Even though this plugin and Quartz both aim to publish notes in websites, we have very different design (explained in a sec), so I generally don't recommend use this plugin together with Quartz. 
If you really want to use Quartz, set `target path` in this plugin's settings to `source/content`, and this plugin will upload your notes into that folder in repo. It may comes with some strange behaviour, because it is not the expected way to use Quartz.

I recommend using a general-propose site generator, such as [Hugo](https://gohugo.io/). Find a [theme](https://themes.gohugo.io/), and use this plugin to upload files to your hugo blog repo. There should be many tutorial on how to init a hugo project and deploy it to github pages. Maybe I'll also write a tutorial on how to use this plugin with hugo, if you are interested, let me know and I'll notify you when it is done.

Back to the design difference. The usage of Quartz is initialize a repo, and use its `source/content` folder as obsidian vault. This plugin has a very differnet use case: I have a large vault, but only want to make a few notes into a website. Thus this plugin picked those notes and transform them, and then any site generator (Hugo, Jekyll, Astro, etc.) can be used to generate the site and deploy it.

**Comment by xplusyi** [comment]
Thanks for your guidence! I would like to try Hugo as you mentioned.
I just found you are from 西安交大！
祝在 UC Berkeley学业有成！

**Comment by yy4382** [comment]
Thanks!
